name: Test Caching

on:
  workflow_dispatch:

jobs:
  save-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        file: ["bla", "blubb"]
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Display Files
        run: tree .
      - name: Create Files
        run: |
          mkdir test
          echo "filename: ${{ matrix.file }}" >> test/${{ matrix.file }}
      - name: Display Files
        run: tree .
      - name: Save Files
        uses: actions/cache/save@v3
        with:
          path: test
          key: cache-test-${{ github.sha }}-${{ matrix.file }}
      - name: Display Files
        run: tree .

  restore-files:
    needs: save-files
    runs-on: ubuntu-latest
    steps:
      - name: Display Files
        run: tree .    
      - name: Restore Files
        uses: actions/cache/restore@v3
        with:
          path: test
          key: cache-test-${{ github.sha }}
          restore-keys: |
            cache-test-${{ github.sha }}-
      - name: Display Files
        run: tree .          
