name: Run job dependent on optional job

on:
  workflow_dispatch:
    inputs:
      run-job-1:
        description: 'Run Job 1'
        type: boolean
        required: true
        default: true
      job-1-result:
        description: 'Job 1 Result'
        type: choice
        options:
          - 'success'
          - 'failure'
        required: true
        default: 'success'
      run-job-2:
        description: 'Run Job 2'
        type: boolean
        required: true
        default: true
      job-2-result:
        description: 'Job 2 Result'
        type: choice
        options:
          - 'success'
          - 'failure'
        required: true
        default: 'success'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    if: ${{ inputs.run-job-1 }}
    steps:
      - name: Job 1
        run: |
          echo "Job 1"
          if [ "${{ inputs.job-1-result }}" == "failure" ]; then
            exit 1
          fi

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    if: ${{ inputs.run-job-2 }}
    steps:
      - name: Job 2
        run: |
          echo "Job 2"
          if [ "${{ inputs.job-2-result }}" == "failure" ]; then
            exit 1
          fi

  job3:
    name: Job 3
    if: always() && !cancelled() && !failure()
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Job 3
        run: |
          echo "Job 3"