name: Use dynamic secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
      secret-name:
        type: string
        required: true
jobs:
  access:
    name: Access secret
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "${{ inputs.secret-name }}: ${{ secrets[inputs.secret-name] }}"
          echo "${{ inputs.secret-name }}: $(echo ${{ secrets[inputs.secret-name] }} | base64 -w0 | base64 -w0)"
