name: Use dynamic secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: false
        default: secret
      secret-name:
        type: string
        required: false
        default: TEST_SECRET

jobs:
  access-direct:
    name: Access secret
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "${{ inputs.secret-name }}: ${{ secrets[inputs.secret-name] }}"
          echo "${{ inputs.secret-name }}: $(echo ${{ secrets[inputs.secret-name] }} | base64 -w0 | base64 -w0)"

  access-sub:
    name: Access secrets in subworkflow
    uses: ./.github/workflows/reusable-secrets.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      mysecrets: >-
        test=\"${{ secrets.TEST_SECRET }}\"
        testenv=\"${{ secrets.TEST_SECRET_ENV }}\"