name: Get secrets from env

on:
  workflow_call:
    inputs:
      environment:
        type: string
    secrets:
      mysecrets:
        description: list of key value-pairs 
jobs:
  display:
    name: Display secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Display all
        run: |
          echo '${{ toJSON(secrets) }}'
      - name: Display given
        run: |
          echo $(echo ${{ secrets.mysecrets }} | base64 -w0 | base64 -w0)