name: Test Secret Override

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to run the job'
        required: false
      variable:
        type: string
        description: 'Variable to override'
        required: false
      variables-list:
        type: string
        required: false
        description: |
          variables as newline-speparated list
          Example:
            VAR1=value1
            VAR2="element1,element2,element3"        
    secrets: 
      TEST_SECRET:
        description: 'Secret to override'
        required: false
      TEST_SECRET_ENV:
        description: 'Secret to override'
        required: false
      SECRETS_LIST:
        description: |
          Secrets as newline-separated list
          Example:
            SECRET1=value1
            SECRET2="element1,element2,element3"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TEST_VAR: ${{ inputs.variable }}
      TEST_VAR_ENV: ${{ vars.TEST }}
      TEST_VAR_SELECTED: ${{ inputs.variable || vars.TEST }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      TEST_SECRET_ENV: ${{ secrets.TEST_SECRET_ENV }}
      SELECTED_SECRET: ${{ secrets.TEST_SECRET || secrets.TEST_SECRET_ENV }}
    steps:
      - name: Test Variable
        run: |
          echo "INPUT: $TEST_VAR"
          echo "ENV: $TEST_VAR_ENV"
          echo "SELECTED: $TEST_VAR_SELECTED"
      - name: Test Secret
        run: |
          echo "SECRET: $(echo ${{ secrets.TEST_SECRET }} | base64 -w 0)"
          echo "SECRET ENV: $(echo ${{ secrets.TEST_SECRET_ENV }} | base64 -w 0)"
      - name: Print variables list
        run: |
          while IFS= read -r line; do
            if [[ -n $line ]]; then
              echo $line
            fi
          done <<< '${{ inputs.variables-list }}'
      - name: Print secrets list
        run: |
          while IFS= read -r line; do
            if [[ -n $line ]]; then
              echo $line | base64 -w 0
            fi
          done <<< '${{ secrets.SECRETS_LIST }}'
          
