name: Create a secret file

on:
  workflow_dispatch:

jobs:
  file:
    name: Create file
    runs-on: ubuntu-latest # deployment target
    steps:
      - name: Create file
        run: |
          echo ${{ secrets.SECRET_FILE }} >> my_secret_file.yml
      - run: ls -lah
      - run: cat my_secret_file.yml

  #deploy:
  #  name: Deploy application
  #  runs-on: ubuntu-latest # deployment target
  #  ...
    
          
