name: Set Secret

on:
  workflow_dispatch:
    inputs:
      value: 
        type: string
        description: "Value of the github secret"

permissions: write-all

jobs:
  set-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      SECRET_VALUE: ${{ inputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set value
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh secret set MYSECRET --body "${SECRET_VALUE:-$(date)}"

  set-env:
    runs-on: ubuntu-latest
    environment: set_secret
    continue-on-error: true
    env:
      SECRET_VALUE: ${{ inputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set value
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh secret set MYSECRET --env set_secret --body "${SECRET_VALUE:-$(date)}"

          
