name: Toplevel Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  context:
    name: Display toplevel context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  
  sub:
    uses: ./.github/workflows/sub.yml

  sub-env-single-line:
    uses: ./.github/workflows/sub.yml
    with:
      environment: vars_secrets
      varlist: >-
        KEY1=${{ vars.MY_VAR }}
        KEY2=${{ vars.MY_VAR2 }}
    secrets:
      secretlist: >-
        SECRET1=${{ secrets.MY_SECRET }}
        SECRET2=${{ secrets.MY_SECRET2 }}

  sub-env-multi-line:
    uses: ./.github/workflows/sub.yml
    with:
      environment: vars_secrets
      varlist: |
        KEY1=${{ vars.MY_VAR }}
        KEY2=${{ vars.MY_VAR2 }}
    secrets:
      secretlist: |
        SECRET1=${{ secrets.MY_SECRET }}
        SECRET2=${{ secrets.MY_SECRET2 }}

